CREATE DATABASE PASSEINESSA;

USE PASSEINESSA;



CREATE TABLE TB_MATERIAS (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NM_MATERIA VARCHAR(5000) NOT NULL,
	NM_CONTEUDO VARCHAR(5000) NOT NULL

);

CREATE TABLE TB_ATIVIDADE (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_MATERIA INT NOT NULL,
    DT_INICIO DATE NOT NULL,
    NM_CONTEUDO VARCHAR(5000),
	NR_HORA int,
    NR_MINUTO int,
	NR_SEGUNDO int,
    FOREIGN KEY (ID_MATERIA) REFERENCES TB_MATERIAS(ID)
);


SELECT * FROM TB_ATIVIDADE;

SELECT * FROM TB_MATERIAS;
